[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "interlinear"
authors = [{name = "John C. G. Sturdy", email = "jcg.sturdy@gmail.com"}]
readme = "README.md"
license = "GPL-3.0-or-later"
version = "0.0.2"
description = "Interlinear text handling."
dynamic = ["dependencies"]
